  on: [push]
  name: Azure ARM
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: rsgrp-mkt-east-pr7ytrg
          template: ./application-insights-mkt-east.json
          parameters: workspaceResourceId=9410b8c3-1d9c-4c48-b3d5-9dc61afd4a68
                      requestSource=IbizaAIExtension
                      tagsArray=["Department":"Marketing","Environment":"Prod","Cost-Center":"CSTPR-MK543","Project":"EcoEnergyCampaign","Team":"IndivResAppDev"]
                      workspaceResourceId=/subscriptions/d8063b4c-5a26-4bb2-a00b-b40ab0c2ba66/resourcegroups/DefaultResourceGroup-EUS/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspace-d8063b4c-5a26-4bb2-a00b-b40ab0c2ba66-EUS

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
